export const COLLECTIONS = {
  USERS:              "users",
  POSTS:              "posts",
  COMMENTS:           "comments",
  MESSAGES:           "messages",
  HABITS:             "habits",
  CHALLENGES:         "challenges",
  CHALLENGE_PROGRESS: "challengeProgress",
  POINTS:             "points",
  REWARDS:            "rewards",
  PRODUCTS:           "products",
  ORDERS:             "orders",
  SUBSCRIPTIONS:      "subscriptions",
  REPORTS:            "reports",
  BUSINESSES:         "businesses",
  NOTIFICATIONS:      "notifications",
  FOLLOWS:            "follows",
  GARDENS:            "gardens",
} as const;
