export const COLLECTIONS = {
  USERS: "users",
  POSTS: "posts",
  COMMENTS: "comments",
  HABITS: "habits",
  CHALLENGES: "challenges",
  CHALLENGE_PROGRESS: "challengeProgress",
  POINTS: "points",
  REWARDS: "rewards",
  REPORTS: "reports",
  BUSINESSES: "businesses",
  NOTIFICATIONS: "notifications",
  FOLLOWS: "follows",
  CIRCLES: "circles",
  CIRCLE_MEMBERSHIPS: "circleMemberships",
  EVENTS: "events",
  EVENT_RSVPS: "eventRsvps",
  SAVED_ITEMS: "savedItems",
  SUBSCRIPTIONS: "subscriptions",
} as const;
